Backup flash firmware
 pbackup <file>q
 Set update files
 pdisk [U <file>]q
Calibrate ADC
 pcal <voltage>q
List out file to screen
 pcat <file>q
Change directory
 pcd <directory name>|..q 
Copy src to dest file
 pcp <src file> <dest file>q
Enter or print date
 pdate [d/m/y|m/d/y|y/m/d]q
Enter or print day
 pday [mon|tue|wed|thu|fri|sat|sun]q
Directory listing
 pdir [*.<filetail>][-w|-d|-m]q
Extract filename from Diskimage
 pext <filename> <diskimage>q
Reset to factory settings
 pfactoryq
Format Diskimage
 pfmt <diskimage>q
Print list of commands
 phelpq
List BPD information 
 pinfo [cmd]q
Insert filename into Diskimage
 pins <filename> <diskimage>q
Directory listing
 pls [*.<filetail>][-w|-d|-m]q
Make directory
 pmkdir <directory name>q
Copy src to dest file
 pmv <src file> <dest file>q
Mount diskimage
 pmnt <[d | e | f | g:diskimage>q
Present directory name
 ppwdq
Reboot the module
 prebootq
Rename src file to dest file
 pren <src file> <dest file>q
Reset the module
 presetq
Delete file
 prm <file> | <*.*>q
Delete directory
 prmdir <directory name>q
Set or print various BPD options
 pset [time <24|ampm> |q 
 pdate <mdy|dmy|ymd> |q  
 plines <1...255> |q 
 psleep <0...60> |q 
 pecho <ON|OFF> |q 
 pupdate <ON|OFF>]q 
Enter or print time
 ptime [hh:mm:ss|hh:mm:ss [a|p]]q
List out file
 ptype <file>q
UnMount diskimage
 pumnt [d | e | f | g]q
Use XMODEM to send a file
xmodt <filename>q
Use XMODEM to receive a file
xmodr [-c] <filename>q
Use XMODEM to receive a file
xmodz [-c] <filename>q