#!/bin/bash

bootdir="sector0"
output_file="${bootdir}.zip"
myname="make_sd"

client_base="https://raw.githubusercontent.com/bkw777/dlplus/master/clients"

trap "echo Build failed!" EXIT

CURLOPTS="-f -s"
CLEANUP=1
VERBOSE=0

while getopts "vn" opt ; do
    case "$opt" in
        v)      VERBOSE=1; CURLOPTS="";
                ;;
        n)      CLEANUP=0;
                ;;
    esac
done

if ! [ -f "${myname}" ]; then
    echo "Error: Only run the build from the SD_builder directory!" >&2
    exit 1
fi

if [ ${BASH_VERSINFO[0]} -lt 4 ] ; then
    echo "Error: script requires bash 4.x or higher!" >&2
    exit 1
fi
set -euo pipefail

rm -rf "${bootdir}"
mkdir "${bootdir}"

echo "Retrieving client intallers..."
for c in teeny ts-dos; do
    for m in 100 200 NEC ; do
        echo "  * ${c^^} ${m}"
        curl $CURLOPTS -S -L -o "${bootdir}/${c^^}.${m}" "${client_base}/${c}/${c^^}.${m}"
        unix2dos -q "${bootdir}/${c^^}.${m}"
        grep -q 'PEEK' "${bootdir}/${c^^}.${m}"
    done
done
c=dskmgr
for m in 100 200 ; do
    echo "  * ${c^^} ${m}"
    curl $CURLOPTS -S -L -o "${bootdir}/${c^^}.${m}" "${client_base}/${c}/${c^^}.${m}"
    unix2dos -q "${bootdir}/${c^^}.${m}"
done

echo "Copying bootstrap..."
cp -f ../bootstrap/BOOT "${bootdir}/BOOT"
unix2dos -q "${bootdir}/BOOT"

echo "Copying help files..."
mkdir "${bootdir}/help"
for i in ../helpfiles/MAN*.DO ; do
    cp "$i" "${bootdir}/help/"
done
unix2dos -q "${bootdir}"/help/MAN*.DO

echo "Creating SD card zip file..."
zip -q -r "${output_file}" "${bootdir}"
unzip -q -t "${output_file}"

if [ $CLEANUP -eq 1 ] ; then
    rm -rf "${bootdir}"
fi
echo "All done!"
trap '' EXIT